import packageJson from '../../package.json';

export const CONFIG = {
  APP_NAME: 'FiTrack',
  APP_VERSION: packageJson.version,
  GITHUB_OWNER: 'AyushSaha184',
  GITHUB_REPO: 'FiTrack',
  UPDATE_CHECK_INTERVAL_MS: 24 * 60 * 60 * 1000, // 24 hours
  DEFAULT_STEP_GOAL: 10_000,
  MIN_STEP_GOAL: 1_000,
  MAX_STEP_GOAL: 100_000,
  DEFAULT_REST_TIME: 90,
  REST_TIMES: [30, 60, 90, 120, 180, 240],
  AUTO_SAVE_DEBOUNCE_MS: 500,
  SEARCH_DEBOUNCE_MS: 300,
  HAPTIC_FEEDBACK_ENABLED: true,
  PULL_TO_REFRESH_ENABLED: true,
  CHART_ANIMATION_DURATION: 600,
  HISTORY_PAGE_SIZE: 30,
  WORKOUT_PAGE_SIZE: 20,
  EXERCISE_LIBRARY_PAGE_SIZE: 50,
  DAILY_STEP_REFRESH_HOUR: 4,
} as const;
