-- Add slug column to exercises table for slug→UUID lookup
ALTER TABLE exercises
  ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;

-- Populate slugs for predefined exercises using their names
-- Names from the initial seed data (001_initial_schema.sql lines 273-401)
UPDATE exercises SET slug = 'barbell-bench-press' WHERE name = 'Barbell Bench Press' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-bench-press' WHERE name = 'Dumbbell Bench Press' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-dumbbell-bench-press' WHERE name = 'Single-Arm Dumbbell Bench Press' AND is_custom = false;
UPDATE exercises SET slug = 'incline-barbell-bench-press' WHERE name = 'Incline Barbell Bench Press' AND is_custom = false;
UPDATE exercises SET slug = 'incline-dumbbell-press' WHERE name = 'Incline Dumbbell Press' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-incline-dumbbell-press' WHERE name = 'Single-Arm Incline Dumbbell Press' AND is_custom = false;
UPDATE exercises SET slug = 'decline-barbell-bench-press' WHERE name = 'Decline Barbell Bench Press' AND is_custom = false;
UPDATE exercises SET slug = 'decline-dumbbell-press' WHERE name = 'Decline Dumbbell Press' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-chest-fly' WHERE name = 'Dumbbell Chest Fly' AND is_custom = false;
UPDATE exercises SET slug = 'incline-dumbbell-fly' WHERE name = 'Incline Dumbbell Fly' AND is_custom = false;
UPDATE exercises SET slug = 'standing-cable-crossover' WHERE name = 'Standing Cable Crossover' AND is_custom = false;
UPDATE exercises SET slug = 'low-to-high-cable-fly' WHERE name = 'Low-to-High Cable Fly' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-cable-chest-press' WHERE name = 'Single-Arm Cable Chest Press' AND is_custom = false;
UPDATE exercises SET slug = 'chest-press-machine' WHERE name = 'Chest Press Machine' AND is_custom = false;
UPDATE exercises SET slug = 'pec-deck-fly' WHERE name = 'Pec Deck Fly' AND is_custom = false;
UPDATE exercises SET slug = 'bodyweight-push-up' WHERE name = 'Bodyweight Push-Up' AND is_custom = false;
UPDATE exercises SET slug = 'deficit-push-up' WHERE name = 'Deficit Push-Up' AND is_custom = false;
UPDATE exercises SET slug = 'chest-dip' WHERE name = 'Chest Dip' AND is_custom = false;
UPDATE exercises SET slug = 'conventional-barbell-deadlift' WHERE name = 'Conventional Barbell Deadlift' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-bent-over-row' WHERE name = 'Barbell Bent-Over Row' AND is_custom = false;
UPDATE exercises SET slug = 'pendlay-row' WHERE name = 'Pendlay Row' AND is_custom = false;
UPDATE exercises SET slug = 'one-arm-dumbbell-row' WHERE name = 'One-Arm Dumbbell Row' AND is_custom = false;
UPDATE exercises SET slug = 'chest-supported-dumbbell-row' WHERE name = 'Chest-Supported Dumbbell Row' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-t-bar-row' WHERE name = 'Barbell T-Bar Row' AND is_custom = false;
UPDATE exercises SET slug = 'wide-grip-lat-pulldown' WHERE name = 'Wide-Grip Lat Pulldown' AND is_custom = false;
UPDATE exercises SET slug = 'close-grip-lat-pulldown' WHERE name = 'Close-Grip Lat Pulldown' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-lat-pulldown' WHERE name = 'Single-Arm Lat Pulldown' AND is_custom = false;
UPDATE exercises SET slug = 'seated-cable-row' WHERE name = 'Seated Cable Row' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-seated-cable-row' WHERE name = 'Single-Arm Seated Cable Row' AND is_custom = false;
UPDATE exercises SET slug = 'straight-arm-cable-pulldown' WHERE name = 'Straight-Arm Cable Pulldown' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-shrug' WHERE name = 'Barbell Shrug' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-shrug' WHERE name = 'Dumbbell Shrug' AND is_custom = false;
UPDATE exercises SET slug = 'chest-supported-dumbbell-shrug' WHERE name = 'Chest-Supported Dumbbell Shrug' AND is_custom = false;
UPDATE exercises SET slug = 'cable-face-pull' WHERE name = 'Cable Face Pull' AND is_custom = false;
UPDATE exercises SET slug = 'pull-up-chin-up' WHERE name = 'Pull-Up / Chin-Up' AND is_custom = false;
UPDATE exercises SET slug = 'inverted-row' WHERE name = 'Inverted Row' AND is_custom = false;
UPDATE exercises SET slug = 'hyperextension-back-extension' WHERE name = 'Hyperextension (Back Extension)' AND is_custom = false;
UPDATE exercises SET slug = 'standing-barbell-overhead-press' WHERE name = 'Standing Barbell Overhead Press (OHP)' AND is_custom = false;
UPDATE exercises SET slug = 'seated-barbell-overhead-press' WHERE name = 'Seated Barbell Overhead Press' AND is_custom = false;
UPDATE exercises SET slug = 'seated-dumbbell-shoulder-press' WHERE name = 'Seated Dumbbell Shoulder Press' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-dumbbell-shoulder-press' WHERE name = 'Single-Arm Dumbbell Shoulder Press' AND is_custom = false;
UPDATE exercises SET slug = 'arnold-press' WHERE name = 'Arnold Press' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-lateral-raise' WHERE name = 'Dumbbell Lateral Raise' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-leaning-lateral-raise' WHERE name = 'Single-Arm Leaning Lateral Raise' AND is_custom = false;
UPDATE exercises SET slug = 'cable-lateral-raise' WHERE name = 'Cable Lateral Raise' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-front-raise' WHERE name = 'Dumbbell Front Raise' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-front-raise' WHERE name = 'Barbell Front Raise' AND is_custom = false;
UPDATE exercises SET slug = 'cable-front-raise' WHERE name = 'Cable Front Raise' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-rear-delt-fly' WHERE name = 'Dumbbell Rear Delt Fly (Bent-Over)' AND is_custom = false;
UPDATE exercises SET slug = 'seated-machine-rear-delt-fly' WHERE name = 'Seated Machine Rear Delt Fly' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-upright-row' WHERE name = 'Barbell Upright Row' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-upright-row' WHERE name = 'Dumbbell Upright Row' AND is_custom = false;
UPDATE exercises SET slug = 'standing-barbell-curl' WHERE name = 'Standing Barbell Curl' AND is_custom = false;
UPDATE exercises SET slug = 'standing-ez-bar-curl' WHERE name = 'Standing EZ-Bar Curl' AND is_custom = false;
UPDATE exercises SET slug = 'standing-dumbbell-curl' WHERE name = 'Standing Dumbbell Curl' AND is_custom = false;
UPDATE exercises SET slug = 'alternating-dumbbell-curl' WHERE name = 'Alternating Dumbbell Curl' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-dumbbell-preacher-curl' WHERE name = 'Single-Arm Dumbbell Preacher Curl' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-preacher-curl' WHERE name = 'Barbell Preacher Curl' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-incline-curl' WHERE name = 'Dumbbell Incline Curl' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-hammer-curl' WHERE name = 'Dumbbell Hammer Curl' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-dumbbell-hammer-curl' WHERE name = 'Single-Arm Dumbbell Hammer Curl' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-concentration-curl' WHERE name = 'Dumbbell Concentration Curl' AND is_custom = false;
UPDATE exercises SET slug = 'cable-bicep-curl' WHERE name = 'Cable Bicep Curl (Rope or Bar)' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-cable-curl' WHERE name = 'Single-Arm Cable Curl' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-reverse-curl' WHERE name = 'Barbell Reverse Curl' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-reverse-curl' WHERE name = 'Dumbbell Reverse Curl' AND is_custom = false;
UPDATE exercises SET slug = 'seated-barbell-wrist-curl' WHERE name = 'Seated Barbell Wrist Curl' AND is_custom = false;
UPDATE exercises SET slug = 'seated-barbell-wrist-extension' WHERE name = 'Seated Barbell Wrist Extension' AND is_custom = false;
UPDATE exercises SET slug = 'close-grip-barbell-bench-press' WHERE name = 'Close-Grip Barbell Bench Press' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-skull-crusher' WHERE name = 'Barbell Skull Crusher (Lying Extension)' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-skull-crusher' WHERE name = 'Dumbbell Skull Crusher' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-dumbbell-skull-crusher' WHERE name = 'Single-Arm Dumbbell Skull Crusher' AND is_custom = false;
UPDATE exercises SET slug = 'overhead-dumbbell-triceps-extension' WHERE name = 'Overhead Dumbbell Triceps Extension' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-overhead-dumbbell-extension' WHERE name = 'Single-Arm Overhead Dumbbell Extension' AND is_custom = false;
UPDATE exercises SET slug = 'overhead-cable-triceps-extension' WHERE name = 'Overhead Cable Triceps Extension' AND is_custom = false;
UPDATE exercises SET slug = 'cable-triceps-pushdown' WHERE name = 'Cable Triceps Pushdown (Rope or Bar)' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-cable-triceps-pushdown' WHERE name = 'Single-Arm Cable Triceps Pushdown' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-triceps-kickback' WHERE name = 'Dumbbell Triceps Kickback' AND is_custom = false;
UPDATE exercises SET slug = 'single-arm-cable-triceps-kickback' WHERE name = 'Single-Arm Cable Triceps Kickback' AND is_custom = false;
UPDATE exercises SET slug = 'triceps-bench-dip' WHERE name = 'Triceps Bench Dip' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-back-squat' WHERE name = 'Barbell Back Squat' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-front-squat' WHERE name = 'Barbell Front Squat' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-goblet-squat' WHERE name = 'Dumbbell Goblet Squat' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-bulgarian-split-squat' WHERE name = 'Barbell Bulgarian Split Squat' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-bulgarian-split-squat' WHERE name = 'Dumbbell Bulgarian Split Squat' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-walking-lunge' WHERE name = 'Barbell Walking Lunge' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-walking-lunge' WHERE name = 'Dumbbell Walking Lunge' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-reverse-lunge' WHERE name = 'Dumbbell Reverse Lunge' AND is_custom = false;
UPDATE exercises SET slug = 'deficit-dumbbell-reverse-lunge' WHERE name = 'Deficit Dumbbell Reverse Lunge' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-step-up' WHERE name = 'Dumbbell Step-Up' AND is_custom = false;
UPDATE exercises SET slug = 'leg-press' WHERE name = 'Leg Press' AND is_custom = false;
UPDATE exercises SET slug = 'single-leg-leg-press' WHERE name = 'Single-Leg Leg Press' AND is_custom = false;
UPDATE exercises SET slug = 'hack-squat' WHERE name = 'Hack Squat' AND is_custom = false;
UPDATE exercises SET slug = 'leg-extension' WHERE name = 'Leg Extension' AND is_custom = false;
UPDATE exercises SET slug = 'single-leg-leg-extension' WHERE name = 'Single-Leg Leg Extension' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-romanian-deadlift' WHERE name = 'Barbell Romanian Deadlift (RDL)' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-romanian-deadlift' WHERE name = 'Dumbbell Romanian Deadlift (RDL)' AND is_custom = false;
UPDATE exercises SET slug = 'single-leg-barbell-rdl' WHERE name = 'Single-Leg Barbell RDL' AND is_custom = false;
UPDATE exercises SET slug = 'single-leg-dumbbell-rdl' WHERE name = 'Single-Leg Dumbbell RDL' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-sumo-deadlift' WHERE name = 'Barbell Sumo Deadlift' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-hip-thrust' WHERE name = 'Barbell Hip Thrust' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-hip-thrust' WHERE name = 'Dumbbell Hip Thrust' AND is_custom = false;
UPDATE exercises SET slug = 'single-leg-hip-thrust' WHERE name = 'Single-Leg Hip Thrust' AND is_custom = false;
UPDATE exercises SET slug = 'seated-leg-curl' WHERE name = 'Seated Leg Curl' AND is_custom = false;
UPDATE exercises SET slug = 'lying-leg-curl' WHERE name = 'Lying Leg Curl' AND is_custom = false;
UPDATE exercises SET slug = 'single-leg-lying-leg-curl' WHERE name = 'Single-Leg Lying Leg Curl' AND is_custom = false;
UPDATE exercises SET slug = 'cable-glute-kickback' WHERE name = 'Cable Glute Kickback' AND is_custom = false;
UPDATE exercises SET slug = 'machine-hip-abduction' WHERE name = 'Machine Hip Abduction' AND is_custom = false;
UPDATE exercises SET slug = 'cable-hip-adduction' WHERE name = 'Cable Hip Adduction' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-standing-calf-raise' WHERE name = 'Barbell Standing Calf Raise' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-standing-calf-raise' WHERE name = 'Dumbbell Standing Calf Raise' AND is_custom = false;
UPDATE exercises SET slug = 'single-leg-dumbbell-calf-raise' WHERE name = 'Single-Leg Dumbbell Calf Raise' AND is_custom = false;
UPDATE exercises SET slug = 'barbell-seated-calf-raise' WHERE name = 'Barbell Seated Calf Raise' AND is_custom = false;
UPDATE exercises SET slug = 'seated-calf-raise-machine' WHERE name = 'Seated Calf Raise Machine' AND is_custom = false;
UPDATE exercises SET slug = 'calf-press-on-leg-press' WHERE name = 'Calf Press on Leg Press Machine' AND is_custom = false;
UPDATE exercises SET slug = 'hanging-leg-raise' WHERE name = 'Hanging Leg Raise' AND is_custom = false;
UPDATE exercises SET slug = 'hanging-knee-raise' WHERE name = 'Hanging Knee Raise' AND is_custom = false;
UPDATE exercises SET slug = 'ab-wheel-rollout' WHERE name = 'Ab Wheel Rollout' AND is_custom = false;
UPDATE exercises SET slug = 'cable-crunch' WHERE name = 'Cable Crunch' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-russian-twist' WHERE name = 'Dumbbell Russian Twist' AND is_custom = false;
UPDATE exercises SET slug = 'decline-bench-crunch' WHERE name = 'Decline Bench Crunch' AND is_custom = false;
UPDATE exercises SET slug = 'weighted-decline-bench-crunch' WHERE name = 'Weighted Decline Bench Crunch' AND is_custom = false;
UPDATE exercises SET slug = 'dumbbell-side-bend' WHERE name = 'Dumbbell Side Bend' AND is_custom = false;
UPDATE exercises SET slug = 'cable-woodchopper' WHERE name = 'Cable Woodchopper' AND is_custom = false;
UPDATE exercises SET slug = 'standard-plank' WHERE name = 'Standard Plank' AND is_custom = false;
UPDATE exercises SET slug = 'side-plank' WHERE name = 'Side Plank' AND is_custom = false;
UPDATE exercises SET slug = 'captains-chair-knee-raise' WHERE name = 'Captain''s Chair Knee Raise' AND is_custom = false;

-- Create index on slug for fast lookup
CREATE INDEX IF NOT EXISTS idx_exercises_slug ON exercises(slug);
